###
GET http://localhost:3000/bank-accounts

###
@bankAccountId1 = 6e4635ce-88d1-4e58-9597-d13fc446ee47

###
GET http://localhost:3000/bank-accounts/{{bankAccountId1}}

### Create a new bank account
POST http://localhost:3000/bank-accounts
Content-Type: application/json

{
    "account_number": "1111",
    "owner_name": "John Doe"
}


###
GET http://localhost:3000/bank-accounts/{{bankAccountId1}}/pix-keys

### Create a new pix key for bank account 1
POST http://localhost:3000/bank-accounts/{{bankAccountId1}}/pix-keys
Content-Type: application/json

{
    "kind": "cpf",
    "key": "1"
}

###
@bankAccountId2 = 51a720b2-5144-4d7f-921d-57023b1e24c1

###
GET http://localhost:3000/bank-accounts/{{bankAccountId2}}

#### Create a new pix key for bank account 2
POST http://localhost:3000/bank-accounts/{{bankAccountId2}}/pix-keys
Content-Type: application/json

{
    "kind": "cpf",
    "key": "2"
}

###
GET http://localhost:3000/bank-accounts/{{bankAccountId1}}/transactions

###
GET http://localhost:3000/bank-accounts/{{bankAccountId2}}/transactions

### Create a new transaction
POST http://localhost:3000/bank-accounts/{{bankAccountId1}}/transactions
Content-Type: application/json

{
    "pix_key_key": "3",
    "pix_key_kind": "cpf",
    "description": "My transaction",
    "amount": 10.00
}