FROM node:20-slim

ARG NEXT_PUBLIC_NEST_API_URL

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node package*.json ./

RUN npm install

COPY --chown=node ./ .

RUN NEXT_PUBLIC_NEST_API_URL=${NEXT_PUBLIC_NEST_API_URL} npm run build

CMD [ "npm", "start" ]